name: Lint workflows

on:
  pull_request:
    paths:
      - .github/workflows/**
      - .github/subscribers.yml
  push:
    branches: [main]
    paths:
      - .github/workflows/**
      - .github/subscribers.yml

permissions:
  contents: read

jobs:
  actionlint:
    runs-on: ubuntu-latest
    env:
      SHELLCHECK_OPTS: -S warning
    steps:
      - uses: actions/checkout@v4
      - uses: docker://rhysd/actionlint:1.7.7
        with:
          args: -color
